name: sales_order
description: A new Flutter project.

version: 1.0.0+17

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http_proxy: ^1.2.1
  firebase_core: ^2.3.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  provider: ^6.0.4
  flutter_svg: ^1.0.3
  number_pagination: ^0.0.3+2
  enhance_stepper: ^0.1.1
  signature: ^5.2.1
  sqflite: ^2.0.2
  intl: ^0.18.0
  image_picker: ^0.8.4+1
  camera: ^0.9.2+2
  path: ^1.7.0
  open_file: ^3.2.1
  path_provider: ^2.0.4
  pdf: ^3.8.4
  url_launcher: ^6.1.10
  file_picker: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - assets/data/

  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/jakarta/jakarta.ttf
